src/Entity/Entana.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EntanaRepository")
 */
class Entana
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_produit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sary;

    /**
     * @ORM\Column(type="integer")
     */
    private $vidiny;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Panier", inversedBy="panier")
     */
    private $panier;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="categ_id")
     */
    private $category;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $QuantiteVendu;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\QuantiteVendu", mappedBy="quantite")
     */
    private $quantiteVendus;

    public function __construct()
    {
        $this->quantiteVendus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreProduit(): ?string
    {
        return $this->titre_produit;
    }

    public function setTitreProduit(string $titre_produit): self
    {
        $this->titre_produit = $titre_produit;

        return $this;
    }

    public function getSary(): ?string
    {
        return $this->sary;
    }

    public function setSary(string $sary): self
    {
        $this->sary = $sary;

        return $this;
    }

    public function getVidiny(): ?int
    {
        return $this->vidiny;
    }

    public function setVidiny(int $vidiny): self
    {
        $this->vidiny = $vidiny;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

   

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getQuantiteVendu(): ?int
    {
        return $this->QuantiteVendu;
    }

    public function setQuantiteVendu(?int $QuantiteVendu): self
    {
        $this->QuantiteVendu = $QuantiteVendu;

        return $this;
    }

    /**
     * @return Collection|QuantiteVendu[]
     */
    public function getQuantiteVendus(): Collection
    {
        return $this->quantiteVendus;
    }


    public function addQuantiteVendus(QuantiteVendu $quantiteVendus): self
    {
        if (!$this->quantiteVendus->contains($quantiteVendus)) {
            $this->quantiteVendus[] = $quantiteVendus;
            $quantiteVendus->setQuantite($this);
        }

        return $this;
    }

    public function removeQuantiteVendus(QuantiteVendu $quantiteVendus): self
    {
        if ($this->quantiteVendus->contains($quantiteVendus)) {
            $this->quantiteVendus->removeElement($quantiteVendus);
            // set the owning side to null (unless already changed)
            if ($quantiteVendus->getQuantite() === $this) {
                $quantiteVendus->setQuantite(null);
            }
        }

        return $this;
    }


}

src/Entity/Panier.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PanierRepository")
 */
class Panier
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Entana", mappedBy="panier")
     */
    private $panier;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="paniers")
     */
    private $user;

    /**
     * @ORM\Column(type="integer")
     */
    private $total;



    public function __construct()
    {
        $this->panier = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Entana[]
     */
    public function getPanier(): Collection
    {
        return $this->panier;
    }

    public function addPanier(Entana $panier): self
    {
        if (!$this->panier->contains($panier)) {
            $this->panier[] = $panier;
            $panier->setPanier($this);
        }

        return $this;
    }

    public function removePanier(Entana $panier): self
    {
        if ($this->panier->contains($panier)) {
            $this->panier->removeElement($panier);
            // set the owning side to null (unless already changed)
            if ($panier->getPanier() === $this) {
                $panier->setPanier(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->total;
    }

    public function setTotal(int $total): self
    {
        $this->total = $total;

        return $this;
    }

}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Entana;
use App\Form\EntanaType;
use App\Repository\EntanaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\Response;


class PanierController extends AbstractController

{
    /*private $urlGenerator;*/
    /**
     * @Route("/panier", name="panier")
     */

    public function index( SessionInterface $session, EntanaRepository $entanaRepository ):Response
    {
        //$session = $request->getSession();
        $panier=$session->get('panier',[]);
        $panierWithData=[];

        foreach ($panier as $id => $quantite) {
           $panierWithData[]=[
                'entana' => $entanaRepository->find($id),
                'quantite' => $quantite
                            ];
        }
        //dd($panierWithData);
        $total = 0;
        $totalQuantite = 0;
        foreach ($panierWithData as $item) {
           $totalItem = $item['entana']->getVidiny()* $item['quantite'];
           $totalQuantite += $item['quantite']; //nampina quantite
           $total += $totalItem;
        }
         return $this->json([
            'code' => 200,
            'message' => 'voavidy',
            'totalQuantite'=>  $totalQuantite
        ],200);

    }

    /**
     * @Route("/panier/add/{id}", name="panier_gestion")
     */
    public function add($id, SessionInterface $session)
    {

    	$panier = $session->get('panier',[]);
    	if(!empty($panier[$id])){
    		$panier[$id]++;
    	}
    	else{$panier[$id]=1;}
    	$session->set('panier',$panier);

        return $this->redirectToRoute('panier'); //mamerina ilay code etsy ambony
    }

}

templates/panier/panier.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello PanierController!{% endblock %}
{% block body %}
<div class="jumbotron">
    {% if items | length >0 %}
    <table class="table">
    	<thead>
    		<tr>
    			<th>entana</th>
    			<th>vidiny</th>
    			<th>quantite</th>
                <th class="text-center">Total</th>
    		</tr>
    	</thead>
    	<tbody>
    		{% for item in items %}

        	<tr>
    			<td>{{ item.entana.titreProduit }}</td>
    			<td>{{ item.entana.vidiny }} Ariary</td>
    			<td>{{ item.quantite }}</td>
    			<td class="text-center">{{ item.entana.vidiny*item.quantite }} Ariary</td>
                <td class="text-center"><a class="del" href="{{path('adm_panier_del',{'id': item.entana.id})}}">
          <button type="button" class="btn-mamafa" style="padding: 0.5rem 1rem;
          font-size: 1.25rem;
          border-radius: 0.3rem;">Manena</button>
      </a></td>
      <td class="text-center"><a class="del" href="{{path('adm_panier_delTotal',{'id': item.entana.id})}}">
          <button type="button" class="btn-danger" style="padding: 0.5rem 1rem;
          font-size: 1.25rem;
          border-radius: 0.3rem;">
          <i class="fas fa-trash"></i> Mamafa</button>
      </a></td>
    		</tr>
    		{% endfor %}
    	</tbody>     
        <tfoot>            
            <tr>
                <td colspan="2" class="text-right">Total:</td>
                <td>{{totalQuantite}}</td>
                <td class="text-center">Total: {{total}} Ariary</td>
                <td class="text-center"><a class="del" href="{{path('adm_payer')}}">
                <button type="button" class="btn-payer" style="padding: 0.5rem 1rem;
                font-size: 1.25rem;
                border-radius: 0.3rem;">Payer</button>
      </a></td>
            </tr>
        </tfoot>
    </table>
    {% else %}
    <h1> Mbola tsy nividy </h1>
    {% endif %}
</div>
{% endblock %}